language: php

php:
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - chmod 777 travis.phpunit.xml
  - mkdir -p build/logs

script:
  - cd $TRAVIS_BUILD_DIR;
  - vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - pwd
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
